version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: chatbot-react-app/dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: chatbot-server-app/dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
