# Stage 1: Build React app
FROM node:18 AS build

WORKDIR /app

COPY chatbot-react-app/package.json chatbot-react-app/package-lock.json ./
RUN npm install
COPY chatbot-react-app ./
RUN npm run build

# Stage 2: Serve React app
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
